# Generated by Django 2.2.24 on 2022-11-09 12:28

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20221006_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.dir_path_name, verbose_name='添付ファイル'),
        ),
    ]
